# Generated by Django 5.2.4 on 2025-08-05 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('coordinator', 'Coordinator'), ('guide', 'Guide')], default='student', max_length=20),
        ),
    ]
