# Generated by Django 5.2.4 on 2025-10-10 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_notification_read_remove_notification_sent_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='deleted_by_sender',
            field=models.BooleanField(default=False),
        ),
    ]
