# Generated by Django 5.2.4 on 2025-10-12 18:15

import django.db.models.deletion
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_customuser_description_customuser_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='event_type',
            field=models.CharField(choices=[('REVIEW', 'Project Review'), ('SUBMISSION', 'Submission Deadline'), ('MEETING', 'Meeting'), ('PROJECT_START', 'Project Start'), ('PROJECT_END', 'Project End'), ('TOPIC_DEADLINE', 'Topic Submission Deadline'), ('PRESENTATION', 'Project Presentation'), ('OTHER', 'Other')], max_length=50),
        ),
        migrations.CreateModel(
            name='ProjectActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('activity_type', models.CharField(choices=[('mini_project', 'Mini Project'), ('major_project', 'Major Project'), ('seminar', 'Seminar'), ('assignment', 'Assignment'), ('research', 'Research Project'), ('internship', 'Internship Project')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('topic_submission_deadline', models.DateTimeField()),
                ('syllabus', models.FileField(blank=True, help_text='Upload syllabus document (max 10MB)', null=True, upload_to=users.models.syllabus_upload_path, validators=[users.models.validate_file_extension])),
                ('guidelines', models.TextField(blank=True)),
                ('max_team_size', models.PositiveIntegerField(default=1)),
                ('min_team_size', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('completed', 'Completed'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('is_visible_to_students', models.BooleanField(default=False)),
                ('department', models.CharField(blank=True, help_text='Department this activity belongs to', max_length=100, null=True)),
                ('assigned_to_all_students', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Project Activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.projectactivity')),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('activity', 'student')},
            },
        ),
        migrations.AddField(
            model_name='projectactivity',
            name='assigned_students',
            field=models.ManyToManyField(blank=True, related_name='assigned_activities', through='users.ProjectAssignment', through_fields=('activity', 'student'), to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TopicSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_title', models.CharField(max_length=300)),
                ('topic_description', models.TextField()),
                ('objectives', models.TextField()),
                ('methodology', models.TextField(blank=True)),
                ('expected_outcomes', models.TextField(blank=True)),
                ('technologies', models.TextField(help_text='Programming languages, frameworks, tools, etc.')),
                ('domain', models.CharField(help_text='Web Development, AI/ML, Data Science, Mobile App, etc.', max_length=100)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proposal_document', models.FileField(blank=True, help_text='Upload proposal document (max 5MB)', null=True, upload_to=users.models.proposal_upload_path, validators=[users.models.validate_file_extension])),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('revision_required', 'Revision Required')], default='draft', max_length=20)),
                ('review_comments', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_submissions', to='users.projectactivity')),
                ('guide', models.ForeignKey(limit_choices_to={'role__in': ['guide', 'admin']}, on_delete=django.db.models.deletion.CASCADE, related_name='guided_topics', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_topics', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
                'unique_together': {('activity', 'submitted_by')},
            },
        ),
        migrations.CreateModel(
            name='EventSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_text', models.TextField(blank=True, help_text='Description or notes about the submission')),
                ('submission_files', models.FileField(blank=True, help_text='Upload submission files', null=True, upload_to=users.models.event_submission_upload_path, validators=[users.models.validate_file_extension])),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('revision_required', 'Revision Required')], default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('grade', models.CharField(blank=True, help_text='Grade: A+, A, B+, B, C+, C, D, F', max_length=10)),
                ('score', models.DecimalField(blank=True, decimal_places=2, help_text='Score out of 100', max_digits=5, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('evaluated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluated_submissions', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='users.calendarevent')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_submissions', to=settings.AUTH_USER_MODEL)),
                ('topic_submission', models.ForeignKey(blank=True, help_text="Link to student's project topic if applicable", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_submissions', to='users.topicsubmission')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_number', models.PositiveIntegerField(help_text='Review 1, Review 2, etc.')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('review_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='users.projectactivity')),
                ('calendar_event', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_review', to='users.calendarevent')),
            ],
            options={
                'ordering': ['review_number'],
                'unique_together': {('activity', 'review_number')},
            },
        ),
    ]
