# Generated by Django 5.2.4 on 2025-10-12 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_calendarevent_event_type_projectactivity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectactivity',
            name='department',
            field=models.CharField(blank=True, help_text='Department this activity belongs to (deprecated)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='projectactivity',
            name='is_visible_to_students',
            field=models.BooleanField(default=True),
        ),
    ]
