# Generated by Django 5.2.4 on 2025-10-12 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_projectactivity_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsubmission',
            name='activity',
            field=models.ForeignKey(blank=True, help_text='Activity (for final reports). Event takes precedence if both are set.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='final_submissions', to='users.projectactivity'),
        ),
        migrations.AlterField(
            model_name='eventsubmission',
            name='event',
            field=models.ForeignKey(blank=True, help_text='Calendar event (for reviews). Null for final reports tied to activity end_date.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='users.calendarevent'),
        ),
    ]
